{
 "title": "Medical LLM Dashboards",
 "time": { "from": "2025-04-30T19:01:27.613Z", "to": "2025-04-30T19:01:36.613Z" },
 "panels": [
  {
   "title": "Medical LLM request duration percentiles (ms)",
   "type": "timeseries",
   "description": "Due to lack of requests, the 3 lines are likely to be the same.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "1000*histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{handler=\"/generate\"}[1m]))",
     "legendFormat": "Median"
    },
    {
     "expr": "1000*histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{handler=\"/generate\"}[1m]))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "1000*histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{handler=\"/generate\"}[1m]))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Medical LLM Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/generate\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Medical LLM Service Monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "1000 * rate(http_request_duration_seconds_sum{handler=\"/generate\", job=\"Medical LLM\"}[1m]) / \nrate(http_request_duration_seconds_count{handler=\"/generate\", job=\"Medical LLM\"}[1m])",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Medical LLM Failing Monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/generate\", status=\"4xx\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{handler=\"/generate\", status=\"5xx\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}