replicaCount: 1

image:
  repository: registry.kube-system.svc.cluster.local:5000/taiwanese-llm-app
  tag: production-1.0.0

service:
  port: 7860
  externalIP: ""   # Placeholder

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "128Mi"

