apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f backend/docker-compose-production.yml convert -co backend
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fastapi-server
  name: fastapi-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fastapi-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f backend/docker-compose-production.yml convert -co backend
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fastapi-server
    spec:
      containers:
        - env:
            - name: HUGGINGFACE_TOKEN
              value: HUGGINGFACE_TOKEN
            - name: IS_FASTAPI_DUMMY
              value: "True"
          image: fastapi-server
          name: fastapi-server
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /root/.cache/huggingface/hub
              name: fastapi-server-cm0
            - mountPath: /app/models
              name: fastapi-server-claim1
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            name: fastapi-server-cm0
          name: fastapi-server-cm0
        - name: fastapi-server-claim1
          persistentVolumeClaim:
            claimName: fastapi-server-claim1
            readOnly: true
