apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose -f backend/docker-compose-production.yml convert -co backend
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fastapi-server
  name: fastapi_server
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: fastapi-server
