apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f backend/docker-compose-production.yml convert -co backend
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: gradio
  name: gradio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gradio
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f backend/docker-compose-production.yml convert -co backend
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: gradio
    spec:
      containers:
        - env:
            - name: FASTAPI_SERVER_URL
              value: http://fastapi_server:8000
            - name: GRADIO_PORT
              value: "7860"
          image: gradio
          name: gradio
          ports:
            - containerPort: 7860
              protocol: TCP
      restartPolicy: Always
