apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ./kompose -f backend/docker-compose-production.yml convert -co backend
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: minio-init
  name: minio-init
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - ' sleep 5 && mc alias set myminio http://minio:9000 your-access-key your-secret-key && mc mb -p myminio/production || echo ''Bucket already exists'' '
      image: minio/mc
      name: minio-init
  restartPolicy: Never
