apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ./kompose -f airflow/docker-compose-airflow.yml convert -co airflow
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: airflow-setup
  name: airflow-setup
spec:
  containers:
    - args:
        - -c
        - airflow db migrate && airflow users create --username admin --firstname Airflow --lastname Admin --role Admin --email airflow@example.com --password airflow
      command:
        - /bin/bash
      env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor
        - name: AIRFLOW__CORE__FERNET_KEY
          value: wmSpjmCJ477jqpJE9BlzuzzI_Cw4P4RRGBZj1KeAPcU=
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: "False"
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: postgresql+psycopg2://user:password@postgres/postgres
      image: apache/airflow:2.9.3-python3.11
      name: airflow-setup
      volumeMounts:
        - mountPath: /opt/airflow/dags
          name: airflow-setup-claim0
        - mountPath: /opt/airflow
          name: airflow-shared
  restartPolicy: Never
  volumes:
    - name: airflow-setup-claim0
      persistentVolumeClaim:
        claimName: airflow-setup-claim0
    - name: airflow-shared
      persistentVolumeClaim:
        claimName: airflow-shared
