apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f airflow/docker-compose-airflow.yml convert -co airflow
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: airflow-scheduler
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f airflow/docker-compose-airflow.yml convert -co airflow
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: airflow-scheduler
    spec:
      containers:
        - args:
            - -c
            - exec airflow scheduler
          command:
            - /bin/bash
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__CORE__FERNET_KEY
              value: wmSpjmCJ477jqpJE9BlzuzzI_Cw4P4RRGBZj1KeAPcU=
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "False"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://user:password@postgres/postgres
            - name: LABEL_STUDIO_URL
              value: http://label-studio:8080
            - name: LABEL_STUDIO_USER_TOKEN
              value: ab9927067c51ff279d340d7321e4890dc2841c4a
            - name: MINIO_PASSWORD
              value: your-secret-key
            - name: MINIO_URL
              value: http://minio:9000
            - name: MINIO_USER
              value: your-access-key
          image: apache/airflow:2.9.3-python3.11
          name: airflow-scheduler
          volumeMounts:
            - mountPath: /opt/airflow/dags
              name: airflow-scheduler-claim0
            - mountPath: /opt/airflow
              name: airflow-shared
      restartPolicy: Always
      volumes:
        - name: airflow-scheduler-claim0
          persistentVolumeClaim:
            claimName: airflow-scheduler-claim0
        - name: airflow-shared
          persistentVolumeClaim:
            claimName: airflow-shared
