apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose -f airflow/docker-compose-airflow.yml convert -co airflow
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: airflow-webserver
  name: airflow-webserver
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
  selector:
    io.kompose.service: airflow-webserver
