apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f labelstudio/docker-compose-labelstudio.yml convert -co labelstudio
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: jupyter
  name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jupyter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f labelstudio/docker-compose-labelstudio.yml convert -co labelstudio
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: jupyter
    spec:
      containers:
        - args:
            - bash
            - -c
            - python3 -m pip install boto3 && start-notebook.sh
          env:
            - name: LABEL_STUDIO_URL
              value: http://label-studio:8080
            - name: LABEL_STUDIO_USER_TOKEN
              value: ab9927067c51ff279d340d7321e4890dc2841c4a
            - name: MINIO_PASSWORD
              value: your-secret-key
            - name: MINIO_URL
              value: http://minio:9000
            - name: MINIO_USER
              value: your-access-key
          image: quay.io/jupyter/minimal-notebook:latest
          name: jupyter
          ports:
            - containerPort: 8888
              protocol: TCP
          volumeMounts:
            - mountPath: /home/jovyan/work
              name: jupyter-claim0
      restartPolicy: Always
      volumes:
        - name: jupyter-claim0
          persistentVolumeClaim:
            claimName: jupyter-claim0
