apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose -f labelstudio/docker-compose-labelstudio.yml convert -co labelstudio
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: jupyter
  name: jupyter
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    io.kompose.service: jupyter
