apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f labelstudio/docker-compose-labelstudio.yml convert -co labelstudio
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: label-studio
  name: label-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: label-studio
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f labelstudio/docker-compose-labelstudio.yml convert -co labelstudio
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: label-studio
    spec:
      containers:
        - env:
            - name: LABEL_STUDIO_PASSWORD
              value: labelstudio
            - name: LABEL_STUDIO_URL
              value: http://label-studio:8080
            - name: LABEL_STUDIO_USERNAME
              value: labelstudio@example.com
            - name: LABEL_STUDIO_USER_TOKEN
              value: ab9927067c51ff279d340d7321e4890dc2841c4a
            - name: POSTGRES_DB
              value: appdb
            - name: POSTGRES_HOST
              value: app-db
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: user
          image: heartexlabs/label-studio:1.16.0
          name: label-studio
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /label-studio/scripts
              name: label-studio-claim0
      restartPolicy: Always
      volumes:
        - name: label-studio-claim0
          persistentVolumeClaim:
            claimName: label-studio-claim0
