all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: /home/yc7690_nyu_edu/.ssh/id_rsa_chameleon
    ansible_user: cc
    ansible_ssh_common_args: "-F /home/yc7690_nyu_edu/.ssh/config"
  hosts:
    node1:
      ansible_host: node1
    node2:
      ansible_host: node2
    node3:
      ansible_host: node3